### ISSUE TITLE
Foreign Key Dependecies

### ISSUE THREAD

**Issue by tughril** [k0kubun/sqldef#172]
## Description

I defilne multipule sql files to use sqldef(psqldef) and run sqldef as below
```
cat *.sql | psqldef 
```
But the order of tables in sql file must define foreign key dependecies, so an error happened.

I want DDLs about foreign keys to be run after DDLs about tables.
If this feature is added, we should not define foreign key dependecies by the order of tables in sql file.
https://github.com/k0kubun/sqldef/blob/c25a58539a88e3adb6138c939fcf9fbfd7e656cd/schema/generator.go#L86

## --export output

```
CREATE TABLE pgschema.user_event (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT user_event_user_id_fkey FOREIGN KEY (user_id) REFERENCES pgschema.user(id)
);
CREATE TABLE pgschema.user (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    PRIMARY KEY ("id"),
);
```

## Input SQL
```
CREATE TABLE pgschema.user_event (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT user_event_user_id_fkey FOREIGN KEY (user_id) REFERENCES pgschema.user(id)
);
```

## Current output
```
2021/11/17 03:25:44 pq: relation "pgschema.user" does not exist
```

## Expected output
```
CREATE TABLE pgschema.user_event (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    PRIMARY KEY ("id")
);
CREATE TABLE pgschema.user (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    PRIMARY KEY ("id")
);
ALTER TABLE "pgschema"."user_event" ADD CONSTRAINT "user_event_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id");
```

**Comment by k0kubun** [comment]
That makes sense. I'll take a look at fixing it.

**Comment by k0kubun** [comment]
Ah wait, when I read this issue first, I thought it was just about `--export` output, but after looking at it, I noticed the `--export` output is fine.

So I guess your proposal is that sqldef should _remove_ the `CONSTRAINT` part from the original create table DDLs and separately run `ALTER TABLE` to apply foreign keys, at least for the case that the dependency is not applied yet. Is that right?

One of the design policies of sqldef is that, when nothing is applied yet, you should be able to successfully apply the same input file by just removing `def` from the sqldef command (e.g. `psqldef -h 127.0.0.1 db < input.sql` → `psql -h 127.0.0.1 db < input.sql`) so that you're not completely locked into sqldef. But if you start relying on that magical behavior, you'll lose the portability of your DDLs. Just to double-check, are you sure you're okay with it?

**Comment by k0kubun** [comment]
Please reopen this when you can provide further input about this issue. Thank you.
