### ISSUE TITLE
Feature request: Add include-file option

### ISSUE THREAD

**Issue by fran-f** [k0kubun/sqldef#246]
Hello there 👋 
I work with a couple of databases that contain tables for different applications, separated using table prefixes. The practice is not great, but it's common on web hosting that offers a single schema.

I can use the [existing `--skip-file` option](https://github.com/k0kubun/sqldef/commit/1c7c2fda91edf4f23338cbba69b8b176a2ce0e5e) to exclude tables with specific prefixes, but that's dangerous and difficult to scale: each project should exclude the tables of all possible other projects in the same schema, as soon as these tables are added.

Would it be possible to add a new option, `--include-file` or similarly-named, that would direct `sqldef` to export or affect only tables that match the patterns in the file? The file itself would follow the same format as the exclude list. "Includes" would be applied before "excludes", so that a table matching both lists would be skipped.

**Comment by k0kubun** [comment]
Perhaps such a file would almost always contain the list of table names that are mentioned in the schema definition file, and it feels redundant to me. To make your life easier, how about adding an option that issues no DROP TABLE statements? Then you will not need to maintain a separate file. When you do need to delete a table, we could support writing DROP TABLE in the schema definition, which I assume you rarely need to use.

**Comment by fran-f** [comment]
> Perhaps such a file would almost always contain the list of table names that are mentioned in the schema definition file, and it feels redundant to me.

Rather than the precise list of table names, it would represent the _boundary_ of action. One of the projects I'm looking at, for example, would use these include lines:
```
ark_.*
legacy_ark_.*
```
and the schema file woud contain a longer list of `ark_...` and `legacy_ark_...` tables. With the include file in place I could feel safe that `sqldef` would not affect any `wp_.*` tables in the same database, without *coupling* this project with the knowledge that someone else installed WordPress.

Regarding `--skip-dangerous-operation` arguments, I have two concerns:
- they generate *exceptional cases* and more work when you actually want to run the dangerous operation, making it difficult to use the tool in an automated environment (e.g., a CI pipeline)
- they increase risk, for example if the option is removed by mistake from a command invocation

The latter point stands for `--dry-run` as well. The default behaviour for `sqldef` is to apply changes, which is less safe than the opposite: dry-run by default, and `--apply-changes` as an explicit switch. Other tools again use two separate explicit commands, for example, `terraform plan` and `terraform apply`.

**Comment by k0kubun** [comment]
I have another thing with a deadline that I need to prioritize this week, so let me leave the next comment a week later or so. Thank you.

**Comment by k0kubun** [comment]
> the schema file woud contain a longer list of ark_... and legacy_ark_... tables.

OK, that makes sense. If you only need to specify two prefixes, I can understand why that feature would be more useful for you.

I'm open to accepting the general idea of your proposal. Regarding the interface, as discussed when I merged `--skip-file` https://github.com/k0kubun/sqldef/pull/221#issuecomment-1097571408, I'm thinking about introducing `--config sqldef.yml` and/or loading something like `.sqldef.yml` in order to allow configuring complicated options like this in a YAML file. Do you have any opinions on it?

> The latter point could be made for --dry-run as well. sqldef's default behaviour is to apply changes, which is less safe than the opposite: dry-run by default, and --apply-changes as an explicit switch. Other tools again use two separate explicit commands, for example, terraform plan and terraform apply, to achieve the same "safety by default".

Yeah, I've developed lots of tools like this and it's a general argument that I see. However, for sqldef specifically, I'm trying to reduce the education cost of this tool by making the CLI as close to the original SQL command as possible. If a `mysqldef` command starts with `mysqldef plan` or `mysqldef apply`, you have to memorize `plan`/`apply`. If you have to specify `--apply` to run `mysqldef`, you have to remember it too. On the other hand, the current design allows you to just add `def` to a normal `mysql` command in many cases.

So I'm reluctant to change the default behavior. One thing I can do here is, if we introduce a config that is loaded by default such as `.sqldef.yml` in a current directory, we could make dry-run the default behavior and allow you to trigger apply with explicit `--apply`. For advanced users who are familiar with sqldef enough to know (future) `.sqldef.yml`, it's probably okay to assume the knowledge of the (future) `--apply` flag. WDYT about this solution if you're also concerned about it?

**Comment by fran-f** [comment]
YAML configuration sounds like a good idea, yes! It would work better than separate skip and include files, I think. Having a default `.sqldef.ini` would mirror MySQL, and could be kept in a project repository. I would expect projects soon to gain more than one though: I would have two or three, for example, customised for different environments.

I see what you mean about mirroring the command line for MySQL and other database. It does make it easy to pick up. I still find the current defaults quite dangerous. What about a warning message and an "Are you sure?" prompt if the tool notices it's going to drop several tables?

For my own use case, a configuration file with a section for "include" or "limit to" patterns would be perfect though. An option to dry-run by default would also be nice to have, but lower priority.

**Comment by k0kubun** [comment]
> What about a warning message and an "Are you sure?" prompt if the tool notices it's going to drop several tables?

It's a good approach to avoid asking users to remember original options. But given that it's a breaking change, I'd like to have more time to think about it. Let me handle this one separately as you said it's a lower priority.

Off-topic: If we show a prompt conditionally, I don't want to limit it to drop statements because it becomes harder to notice its existence.

> For my own use case, a configuration file with a section for "include" or "limit to" patterns would be perfect though.

Could you test this? https://github.com/k0kubun/sqldef/pull/250

**Comment by fran-f** [comment]
Finally found a moment to get the environment set up, and build the pull request version! Config file + `target_tables` worked well, thank you. I tried it against a couple of different schemas, and it feels natural as a way to limit the scope of changes.

The option doesn't seem to affect the output of `/export`. I think it would be useful if it did, as a way to produce a focussed schema, but also to rapidly test configuration changes: "which tables would these pattern target? oh, these!"

Thank for your work 🙇

**Comment by k0kubun** [comment]
I updated https://github.com/k0kubun/sqldef/pull/250 to respect `target_tables` on `--export`. Could you check the branch again?

**Comment by fran-f** [comment]
Looks great! Running `mysqldef /config config-with-target-table.yml [...] /export | grep CREATE` is perfect for listing all tables covered by the patterns in the configuration.

**Comment by k0kubun** [comment]
Thanks. Released sqldef v0.12.0 with this feature.

**Comment by fran-f** [comment]
Thank you! 🙇
