### ISSUE TITLE
Retrocompatibility versions from v0.11.49

### ISSUE THREAD

**Issue by ervitis** [k0kubun/sqldef#253]
Hi! We are using `sqldef` v0.11.49 and we are having some troubles when creating some indexes in the postgresql database, so we tried updating the library to the last version but it generated some breaking changes in the API in these commits:

- https://github.com/k0kubun/sqldef/commit/ff675257a6f0916d1235542ad6c0a38f2c035def
- https://github.com/k0kubun/sqldef/commit/969f9d486000716f898ed6dec3200affff454a12
- https://github.com/k0kubun/sqldef/commit/e9ea2faf782e514f0d4cf1bb137f92c8a6c2586a

Is it possible to continue using the functions before those changes without breaking the API? Like golang is doing with the function `ReadAll` from the packages `ioutil` and `io`?

Thank you so much

**Comment by k0kubun** [comment]
I don't understand how you intend to use sqldef. Can you point me to your code using sqldef?

Also, sqldef is not intended to be a library. You're supposed to use CLI as the primary interface to interact with it, I believe I made no breaking changes at the CLI level, and you have to keep up with internal API changes at your own risk if you decide to do that. Please ignore the version because it's for CLI versioning, and you should consider it a major update in terms of internal APIs.

**Comment by k0kubun** [comment]
Also for your information, I'm planning on completely replacing the entire parser for PostgreSQL https://github.com/k0kubun/sqldef/pull/241, and that's why I've been doing those changes. It's currently blocked by an issue in cross-compilation, but as soon as it's cleared out, I'll definitely do that change for the best behavior of sqldef: perfect compatibility with PostgreSQL's parser.

You might be able to expect some stability after that (no guarantee though), but for now, it's a no to:

> Is it possible to continue using the functions before those changes without breaking the API?

**Comment by ervitis** [comment]
Hi @k0kubun, thanks for your fast reply. 

Sure, I want to extend the usability of sqldef using its functions, as you can do it with docker API or other applications. So I don't plan to use it as a cli only. I see your point about your way of versioning as a CLI, but internally, if someone else wants to extend your functionality it does.
